name: Release
on:
  push:
    tags: ["v*"]

permissions:
  id-token: write
  attestations: write
  contents: write    

jobs:
  release:
    runs-on: windows-2022
    environment: actions
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-cache"

      - name: Build HeadsetControl
        run: |
          wget https://github.com/Sapd/HeadsetControl/releases/download/3.1.0/headsetcontrol-windows-x86_64.zip
          unzip headsetcontrol-windows-x86_64.zip headsetcontrol.exe

      - run: cargo build --release

      - run: ISCC ./installer.iss
            # result in ./Output/ArctisBatteryIndicatorSetup.exe

      - name: Sign executable
        env:
          CERTIFICATE_PFX_BASE64: ${{ secrets.CERTIFICATE_PFX_BASE64 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        shell: pwsh
        run: |
          # Decode and save certificate
          [Convert]::FromBase64String($env:CERTIFICATE_PFX_BASE64) | Set-Content -Path certificate_from_secret.pfx -AsByteStream

          # Sign the executable
          $SignTool = Get-ChildItem -Path "C:\\Program Files*\\Windows Kits\\*\\bin\\*\\x64\\signtool.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
          $SignToolPath = $SignTool.FullName
          & $SignToolPath sign /f certificate_from_secret.pfx /p $env:CERTIFICATE_PASSWORD /tr http://timestamp.digicert.com /td sha256 /fd sha256 "Output/ArctisBatteryIndicatorSetup.exe"
          # Clean up certificate
          Remove-Item certificate_from_secret.pfx

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "Output/ArctisBatteryIndicatorSetup.exe"

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            Output/ArctisBatteryIndicatorSetup.exe

          generate_release_notes: true
          draft: true
          name: Release ${{github.ref_name}}
